services:

  php:
    build: docker/php
    container_name: php-fpm
    tty: true
    volumes:
      - ./:/var/www/app
      - ./docker/php/z-overrides.ini:/usr/local/etc/php/conf.d/z-overrides.ini
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - psql
    networks:
      - db-network
      - web-network
    env_file:
      .env

  nginx:
    image: nginx:1.27.5
    container_name: nginx
    tty: true
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www/app
    ports:
      - "${NGINX_EXTERNAL_PORT:-3007}:80"
    depends_on:
      - php
    networks:
      - web-network
    env_file:
      .env

  psql:
    image: postgres:17.6
    container_name: psql
    restart: always
    ports:
      - "${DB_EXTERNAL_PORT:-3008}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./volumes/psql:/var/lib/postgresql
    networks:
      - db-network
    env_file:
      .env
  psqltest:
    image: postgres:17.6
    container_name: psqltest
    restart: always
    ports:
      - "${DB_EXTERNAL_PORT:-3009}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - db-network
    env_file:
      .env

networks:
  db-network:
    driver: bridge
  web-network:
    driver: bridge